quarkus.datasource.user-store.db-kind=postgresql
quarkus.datasource.user-store.username=postgres
quarkus.datasource.user-store.password=root
quarkus.datasource.user-store.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.user-store.jdbc.driver=org.postgresql.xa.PGXADataSource
quarkus.datasource.user-store.jdbc.transactions=xa
quarkus.datasource.user-store.jdbc.acquisition-timeout=30
