import NextAuth from "next-auth";
import { authOptions } from "@/lib/auth";

// This file simply exports the handlers generated by NextAuth.js
// It uses the configuration from `lib/auth.ts`
const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
